services:
  minitwitimage:
    image: nikolatilgreen/minitwitimage
    container_name: minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - sqlite_data:/minitwit/data


volumes:
  sqlite_data:

