services:
  minitwitimage:
    image: nikolai/minitwitimage
    container_name: minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5114:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    networks:
      - itu-minitwit_default
  
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9091"
    networks:
      - itu-minitwit_default

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - itu-minitwit_default

  postgres:
    image: postgres:16
    container_name: test_postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d testdb "]
      interval: 5s
      timeout: 10s
      retries: 5

  test-runner:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    container_name: dotnet_test_runner
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "cd tests/minitwit.tests &&
      dotnet restore && 
      dotnet test"
    environment:
      - ConnectionStrings__DefaultConnection=Host=test_postgres;Port=5432;Database=testdb;Username=testuser;Password=testpassword


networks:
  itu-minitwit_default:
    driver: bridge