services:
  minitwitimage:
    image: nikolai/minitwitimage
    container_name: minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5114:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=testdb;Username=postgres;Password=testpassword
    networks:
      - itu-minitwit_default
  
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d testdb " ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - itu-minitwit_default
        
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    networks:
      - itu-minitwit_default

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3001:3000"
    networks:
      - itu-minitwit_default
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_ROOT_URL=http://0.0.0.0:3001

networks:
  itu-minitwit_default:
    driver: bridge
    
volumes:
  prometheus_data:
  grafana_data: