services:
  webserver:
    image: minitwit-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./src/minitwit.web/minitwit.db:/app/data/minitwit.db


volumes:
  sqlite_data:

