services:
  dbserver:
    image: minitwit/dbserver
    ports:
      - "27018:27017"
    networks:
      - outside

  webserver:
    image: minitwit/webserver
    ports:
      - "5114:5000"
    networks:
        - outside

networks:
  outside:
    name: minitwit-network
    external: true