version: '3'
services:
  dbserver:
    image: minitwit/dbserver
    ports:
      - "27017:27017"
    networks:
      - outside

  webserver:
    image: minitwit/webserver
    ports:
      - "5114:5000"
    networks:
        - outside

  clidownload:
    image: appropriate/curl
    networks:
      - outside
    entrypoint: sh -c  "sleep 5 && curl http://localhost:5114"

networks:
  outside:
    external:
      name: minitwit-network