global:
  scrape_interval:     120s # By default, scrape targets every 120 seconds.
  evaluation_interval: 120s # Evaluate rules every 120 seconds.

  # Attach these extra labels to all timeseries collected by this Prometheus instance.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 120 seconds.
    scrape_interval: 120s

    static_configs:
      - targets: ['prometheus:9091']

  - job_name:       'itu-minittwit-app'

    # Override the global default and scrape targets from this job every 120 seconds.
    scrape_interval: 120s

    static_configs:
      - targets: ['minitwit:8080']
        