services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200"
    networks:
      - itu-minitwit-logging_default
    
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5012:5012"
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      SINK__TCP__URL: "tcp://logstash:5012"
    depends_on:
      - elasticsearch
    networks:
      - itu-minitwit-logging_default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    ports:
      - "5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - itu-minitwit-logging_default
    
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro 
      - ./htpsswd:/etc/nginx/htpsswd:ro
    ports:
      - "8080:8080"
    depends_on:
      - kibana
    networks:
      - itu-minitwit-logging_default

volumes:
  esdata:

networks:
  itu-minitwit-logging_default:
    driver: bridge
