services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    networks:
      - itu-minitwit_default

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - itu-minitwit_default

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - itu-minitwit_default
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0
      - GF_SERVER_ROOT_URL=http://164.90.240.84:3000  
        
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - itu-minitwit_default
  
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: logstash
    volumes:
      - ../logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ../logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "5012:5012"
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    networks:
      - itu-minitwit_default

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - itu-minitwit_default

networks:
  itu-minitwit_default:
    driver: bridge
    
volumes:
  esdata:
  prometheus_data:
  grafana_data: