name: Markdown to PDF

on:
  push:
    branches:
      - report-workflow
  pull_request:
    branches:
      - report-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Convert Markdown to PDF
        run: |
          pandoc report/report.md -o report/build/report.pdf --pdf-engine=xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: report-pdf
          path: report/build/report.pdf