name: Markdown to PDF

on:
  push:
    branches:
      - report-workflow
  pull_request:
    branches:
      - report-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Create build directory
        run: mkdir -p build

      - name: Convert Markdown to PDF
        run: |
          pandoc report/report.md -o build/report.pdf --pdf-engine=xelatex

      - name: Commit report
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f build/report.pdf
          git commit -m "Updated PDF from CI"
          git push